// <auto-generated />
namespace JobLinking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_UserIdRelation_In_JobSeekerAndCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_UserIdRelation_In_JobSeekerAndCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "202309122021563_Added_UserIdRelation_In_JobSeekerAndCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
