// <auto-generated />
namespace JobLinking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_JobTitle_To_JobAd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_JobTitle_To_JobAd));
        
        string IMigrationMetadata.Id
        {
            get { return "202309142300494_Added_JobTitle_To_JobAd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
